<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeadVault.Core\DeadVault.Core.csproj" />
    <ProjectReference Include="..\DeadVault.Store\DeadVault.Store.csproj" />
  </ItemGroup>

</Project>
